name: Hello World!
'on':
  push:
    branches: '*'
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello World"
  tell_date_job:
    runs-on: ubuntu-latest
    steps:
      - name: Now it is
        run: date
  directory_content:
    runs-on: ubuntu-latest
    steps:
      - name: Directory content
        run: ls -l