name: Simple Deployment pipeline
'on':
    push:
        branches: '*'
jobs:
    simple_deployment_pipeline:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
            - uses: superfly/flyctl-actions/setup-flyctl@master
              with:
                node-version: '20'
            - name: Install dependencies
              run: npm install
            - name: Check style
              run: npm run eslint
            - name: production build
              run: npm run build
            - name: test
              run: npm test

            - name: Deploy app
              run: flyctl deploy --remote-only
              env:
                FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }} 




            